#ifndef NN_H
#define NN_H

// Public umbrella header — all library components
// Include path: -I<root>/include
#include "core/tensor.h"
#include "core/layer.h"
#include "core/model.h"
#include "activations/activations.h"
#include "optimizers/optimizer.h"
#include "optimizers/optimizer_extended.h"
#include "optimizers/scheduler.h"
#include "optimizers/one_cycle_lr.h"
#include "optimizers/lookahead.h"
#include "utils/grid_search.h"
#include "utils/tokenizer.h"
#include "utils/gradient_check.h"
#include "utils/numerical_stability.h"
#include "utils/timing_benchmark.h"
#include "utils/serialization_roundtrip.h"
#include "utils/label_smoothing.h"
#include "utils/clip_grad_norm.h"
#include "utils/focal_loss.h"
#include "utils/tabular_ensemble.h"
#include "utils/adaboost.h"
#include "utils/gradient_boosting.h"
#include "utils/elastic_net.h"
#include "utils/random_forest.h"
#include "utils/isolation_forest.h"
#include "utils/lightgbm_style.h"
#include "utils/mixup_cutmix.h"
#include "utils/triplet_loss_siamese.h"

// Layers — convolutional
#include "layers/convolutions/conv_layer.h"
#include "layers/pooling/pool_layer.h"
#include "layers/utility/conv1d.h"
#include "layers/utility/coordconv.h"

// Layers — recurrent
#include "layers/recurrent/lstm.h"
#include "layers/recurrent/rnn.h"
#include "layers/recurrent/gru.h"
#include "layers/recurrent/lstm_bidirectional.h"
#include "layers/recurrent/mamba.h"
#include "layers/recurrent/xlstm.h"
#include "layers/recurrent/mamba2.h"
#include "layers/recurrent/rwkv.h"
#include "layers/recurrent/retnet.h"
#include "layers/recurrent/mlstm.h"

// Layers — dense / embeddings
#include "layers/dense/embedding.h"
#include "layers/dense/flatten.h"

// Layers — normalization
#include "layers/normalization/batch_norm.h"
#include "layers/normalization/layer_norm.h"
#include "layers/normalization/rms_norm.h"
#include "layers/normalization/weight_norm.h"
#include "layers/normalization/group_norm.h"
#include "layers/normalization/spectral_norm.h"
#include "layers/normalization/cbam.h"
#include "layers/normalization/eca.h"
#include "layers/normalization/coord_attention.h"
#include "layers/normalization/scconv.h"
#include "layers/normalization/crate.h"

// Layers — attention
#include "layers/attention/transformer.h"
#include "layers/attention/flash_attention.h"
#include "layers/attention/linformer.h"
#include "layers/attention/nystrom_attention.h"
#include "layers/attention/rope.h"
#include "layers/attention/gat.h"
#include "layers/attention/performer.h"
#include "layers/attention/gqa.h"
#include "layers/attention/layer_output_tracker.h"

// Layers — architectures (full model definitions)
#include "layers/architectures/resnet.h"
#include "layers/architectures/vit.h"
#include "layers/architectures/unet.h"
#include "layers/architectures/squeezenet.h"
#include "layers/architectures/densenet.h"
#include "layers/architectures/mobilenet_v2.h"
#include "layers/architectures/memory_network.h"
#include "layers/architectures/mixture_of_experts.h"
#include "layers/architectures/multi_output_model.h"
#include "layers/architectures/lstm_las.h"
#include "layers/architectures/seq2seq_attention.h"
#include "layers/architectures/cnn_models.h"
#include "layers/architectures/cnn_models_vgg.h"
#include "layers/architectures/patchy_san.h"
#include "layers/architectures/pna.h"
#include "layers/architectures/edgeconv.h"
#include "layers/architectures/dmon.h"
#include "layers/architectures/gmlp.h"
#include "layers/architectures/lightgcn.h"
#include "layers/architectures/deep_gcn.h"

// Layers — utility
#include "layers/utility/skip_connection.h"
#include "layers/utility/squeeze_excitation.h"
#include "layers/utility/dataloader.h"
#include "layers/utility/fourier_features.h"
#include "layers/utility/coord_network.h"
#include "layers/utility/swiglu.h"
#include "layers/utility/ghost_module.h"
#include "layers/utility/spatial_dropout.h"
#include "layers/utility/conv1d.h"
#include "layers/utility/conv1d_transpose.h"
#include "utils/trainer.h"
#include "layers/utility/weight_init.h"

// Layers — generative
#include "layers/generative/vae.h"
#include "layers/generative/capsnet.h"
#include "layers/generative/wgan_gp.h"
#include "layers/generative/ddpm.h"
#include "layers/generative/consistency.h"
#include "layers/generative/affine_coupling.h"
#include "layers/generative/coupling_layer.h"

// Layers — graph
#include "layers/architectures/gnn.h"
#include "layers/architectures/gin.h"
#include "layers/architectures/s4.h"

#endif