#ifndef HYPER_MIXING_H
#define HYPER_MIXING_H

#include "../../core/layer.h"
#include "../normalization/layer_norm.h"
#include <vector>
#include <memory>
#include <stdexcept>

// ============================================================================
// HyperMixing — Mai et al. 2024, "HyperMixing: A Complement to Attention"
// (https://arxiv.org/abs/2401.09656).
//
// HyperMixing is a drop-in attention alternative that mixes token information
// using a (T, T) matrix R generated by a small hypernetwork from the input.
//
// Per block (single HyperMixingLayer):
//   x = input                                                 // (T, d_model)
//   R_logits = W_h · x                                        // (T, T)
//   R      = row_softmax(R_logits)                            // (T, T) rows sum to 1
//   U      = W_2 · σ(W_1 · x)                                 // (T, d_model), σ = GELU
//   H_T    = R @ U                                            // (T, d_model) — token mix
//   Z      = W_4 · σ(W_3 · H_T)                               // (T, d_model) — channel mix
//   out    = LayerNorm(Z + x)                                 // (T, d_model) — pre-norm residual
//
// Activation note: the paper uses GLU activation. We use GELU to match the
// existing repo convention (Dense + LayerNorm stack); GELU is empirically
// comparable for our purposes.
//
// IMPORTANT — `num_tokens` is fixed at construction time. The hypernetwork's W_h
// has output dim = num_tokens, so the layer is bound to one specific T.
// Variable T requires reconstructing the layer. (Matches the paper's
// "T is a hyperparameter" convention.)
//
// This is the simplest attention-free token-mixing layer in the repo. The
// paper's best results pair HyperMixing WITH attention, not as a full
// replacement; our standalone HyperMixingModel demonstrates the architecture
// but is not a recommended end-user config.
// ============================================================================

class HyperMixingLayer : public Layer {
public:
    size_t d_model_;
    size_t mlp_hidden_;
    size_t num_tokens_;

    // Hypernetwork: W_h : (d_model -> num_tokens). R_logits = x · W_h^T.
    Dense W_h_;                                            // weights (num_tokens, d_model)

    // Channel MLP (per-token 2-layer Dense with GELU): (d -> mlp_hidden -> d).
    Dense W_1_;                                            // weights (mlp_hidden, d_model)
    Dense W_2_;                                            // weights (d_model, mlp_hidden)

    // Channel mixing (post token-mix 2-layer Dense with GELU): (d -> mlp_hidden -> d).
    Dense W_3_;                                            // weights (mlp_hidden, d_model)
    Dense W_4_;                                            // weights (d_model, mlp_hidden)

    // Final LayerNorm (pre-norm residual).
    LayerNorm final_ln_;

    // Forward caches (for backward) — exposed for tests.
    Tensor last_input;             // (T, d_model)
    Tensor last_R_logits;          // (T, num_tokens)
    Tensor last_R;                 // (T, num_tokens) — softmax
    Tensor last_U_pre;             // (T, mlp_hidden) — pre-GELU (W_1 · x)
    Tensor last_U;                 // (T, mlp_hidden) — post-GELU
    Tensor last_H_T;               // (T, d_model) — token-mixed
    Tensor last_Z_pre;             // (T, mlp_hidden) — pre-GELU (W_3 · H_T)
    Tensor last_Z;                 // (T, d_model) — channel-mixed, pre-LN
    Tensor last_residual;          // (T, d_model) — Z + x (input to LN)

    HyperMixingLayer(size_t d_model, size_t mlp_hidden, size_t num_tokens);
    ~HyperMixingLayer() override = default;

    Tensor forward(const Tensor& input) override;
    Tensor backward(const Tensor& grad_output, double learning_rate) override;
    void update_weights(double learning_rate) override;
    void zero_grad() override;
    std::vector<Tensor*> parameters() override;
    std::vector<Tensor*> gradients() override;
    Tensor get_weights() const override { return W_h_.weights; }
    Tensor get_gradients() const override { return W_h_.grad_weights; }
    std::string name() const override { return "HyperMixingLayer"; }

    // Copy all learnable parameters (W_h, W_1, W_2, W_3, W_4, final_ln) from
    // `other` into this layer. Both layers must have identical config.
    void copy_params_from(const HyperMixingLayer& other);

    // Accessors.
    size_t d_model()     const { return d_model_; }
    size_t mlp_hidden()  const { return mlp_hidden_; }
    size_t num_tokens()  const { return num_tokens_; }
};

// Stack of `num_layers` HyperMixingLayer blocks + final LayerNorm + classifier.
class HyperMixingModel : public Layer {
public:
    size_t input_dim_;
    size_t d_model_;
    size_t output_dim_;
    size_t num_layers_;
    size_t mlp_hidden_;
    size_t num_tokens_;

    Dense embed_;
    std::vector<std::unique_ptr<HyperMixingLayer>> blocks_;
    LayerNorm final_ln_;
    Dense classifier_;

    HyperMixingModel(size_t input_dim, size_t d_model, size_t output_dim,
                     size_t num_layers, size_t mlp_hidden, size_t num_tokens);

    Tensor forward(const Tensor& input) override;
    Tensor backward(const Tensor& grad_output, double learning_rate) override;
    void update_weights(double learning_rate) override;
    void zero_grad() override;
    std::vector<Tensor*> parameters() override;
    std::vector<Tensor*> gradients() override;
    Tensor get_weights() const override { return embed_.weights; }
    Tensor get_gradients() const override { return embed_.grad_weights; }
    std::string name() const override { return "HyperMixingModel"; }
};

#endif // HYPER_MIXING_H